### ISSUE TITLE
EXCEPTION of type 'KeyError' occurred with message: ''_dataframes''

### ISSUE THREAD

**Issue by yangxuelei** [teto/pymptcpanalyzer#18] opened 2019-04-25 02:44 UTC
Trying to create a throughput plot fails with Python exception EXCEPTION of type 'KeyError' occurred with message: ''_dataframes'':

iperf-mptcp-0-0.pcap> plot throughput mptcp --display 20000
>>> throughput mptcp --display 20000
Traceback (most recent call last):
  File "/home/long/.local/lib/python3.6/site-packages/cmd2/cmd2.py", line 1742, in onecmd_plus_hooks
    stop = self.onecmd(statement)
  File "/home/long/.local/lib/python3.6/site-packages/cmd2/cmd2.py", line 2050, in onecmd
    stop = func(statement)
  File "/home/long/.local/lib/python3.6/site-packages/cmd2/cmd2.py", line 222, in cmd_wrapper
    return func(cmd2_instance, args, unknown)
  File "/home/long/.local/lib/python3.6/site-packages/mptcpanalyzer-0.3-py3.6.egg/mptcpanalyzer/cli.py", line 1126, in do_plot
    dataframes = dargs.pop("_dataframes")
KeyError: '_dataframes'
EXCEPTION of type 'KeyError' occurred with message: ''_dataframes''

* mptcpanalyzer version ($ mptcpanalyzer --version): 0.3
* tshark version ($ tshark --version): 3.1.0

Output of mptcpanalyzer -dDEBUG:
()
{'help': 'Filter flows according to their direction(towards the client or the server)Depends on mptcpstream', 'dest': 'dest', 'option_strings': ['--dest']}
destinations dest
()
{'metavar': 'destination', 'help': 'Filter flows according to their direction(towards the client or the server)Depends on mptcpstream', 'dest': 'pcap_destinations', 'option_strings': ['--dest']}
destinations pcap_destinations
()
{'metavar': 'destination', 'help': 'Filter flows according to their direction(towards the client or the server)Depends on mptcpstream', 'dest': 'pcap_destinations', 'option_strings': ['--dest']}
destinations pcap_destinations
()
{'metavar': 'destination', 'help': 'Filter flows according to their direction(towards the client or the server)Depends on mptcpstream', 'dest': 'pcap_destinations', 'option_strings': ['--dest']}
destinations pcap_destinations
Setting log level to DEBUG
DEBUG:root:Starting in folder /home/long/mptcpanalyzer
DEBUG:root:Pandas version: 0.24.2
DEBUG:root:cmd2 version: 0.9.12
use numexpr? False
found extension EntryPoint.parse('dss = mptcpanalyzer.plots.dss:DSSOverTime')
DEBUG:stevedore.extension:found extension EntryPoint.parse('dss = mptcpanalyzer.plots.dss:DSSOverTime')
DEBUG:matplotlib:CACHEDIR=/home/long/.cache/matplotlib
DEBUG:matplotlib.font_manager:Using fontManager instance from /home/long/.cache/matplotlib/fontlist-v300.json
DEBUG:matplotlib.pyplot:Loaded backend TkAgg version unknown.
found extension EntryPoint.parse('mptcp_attr = mptcpanalyzer.plots.dsn:PlotSubflowAttribute')
DEBUG:stevedore.extension:found extension EntryPoint.parse('mptcp_attr = mptcpanalyzer.plots.dsn:PlotSubflowAttribute')
found extension EntryPoint.parse('owd = mptcpanalyzer.plots.owd:TcpOneWayDelay')
DEBUG:stevedore.extension:found extension EntryPoint.parse('owd = mptcpanalyzer.plots.owd:TcpOneWayDelay')
found extension EntryPoint.parse('reinject = mptcpanalyzer.plots.reinjections:PlotMpTcpReinjections')
DEBUG:stevedore.extension:found extension EntryPoint.parse('reinject = mptcpanalyzer.plots.reinjections:PlotMpTcpReinjections')
found extension EntryPoint.parse('tcp_attr = mptcpanalyzer.plots.dsn:PlotTcpAttribute')
DEBUG:stevedore.extension:found extension EntryPoint.parse('tcp_attr = mptcpanalyzer.plots.dsn:PlotTcpAttribute')
found extension EntryPoint.parse('throughput = mptcpanalyzer.plots.throughput:SubflowThroughput')
DEBUG:stevedore.extension:found extension EntryPoint.parse('throughput = mptcpanalyzer.plots.throughput:SubflowThroughput')
found extension EntryPoint.parse('stats = mptcpanalyzer.command_example:CommandExample')
DEBUG:stevedore.extension:found extension EntryPoint.parse('stats = mptcpanalyzer.command_example:CommandExample')
()
{'metavar': 'destination', 'help': 'Filter flows according to their direction(towards the client or the server)Depends on mptcpstream', 'dest': 'pcap_destinations', 'option_strings': ['--dest']}
destinations pcap_destinations
()
{'metavar': 'destination', 'help': 'Filter flows according to their direction(towards the client or the server)Depends on mptcpstream', 'dest': 'pcap_destinations', 'option_strings': ['--dest']}
destinations pcap_destinations
()
{'metavar': 'destination', 'help': 'Filter flows according to their direction(towards the client or the server)Depends on mptcpstream', 'dest': 'pcap_destinations', 'option_strings': ['--dest']}
destinations pcap_destinations
()
{'metavar': 'destination', 'help': 'Filter flows according to their direction(towards the client or the server)Depends on mptcpstream', 'dest': 'pcap_destinations', 'option_strings': ['--dest']}
destinations pcap_destinations
WARNING: mptcpanalyzer may require a custom wireshark. Check github for mptcp patches streaming.
INFO:root:Starting interactive mode
DEBUG:root:Loading history from /home/long/.local/share/mptcpanalyzer.lst

# how to reproduce
mptcpanalyzer --load examples/iperf-mptcp-0-0.pcap
plot throughput mptcp --display 20000

Link to the incriminated pcap (if possible/relevant):
(part of examples)

**Comment by teto** [comment] 2019-04-25 07:36
thanks for the report, it's actually one plot I am developing so not working yet. For the longest time, this project was kind of personal but now that it has some interesting features, I want to share it with the community, fixing the rough edges. Sadly I am still in the phase where I need to update the README, fix the tests before having a robust release. Next version should follow better development practice.

**Comment by dreibh** [comment] 2019-04-25 08:19
I can confirm the issue reported above for Ubuntu 18.04.

On Ubuntu 19.04, the result is different (but without success as well):
iperf-mptcp-0-0.pcap> plot throughput mptcp 1s --display
>>> throughput mptcp 1s --display
Problem when calling plotter.run
We passed the following arguments:
{}
{'plot_type': 'throughput', 'protocol': 'mptcp', 'window': '1s', 'out': None, 'display': True, 'title': None, 'primary': False, 'styles': [], '__statement__': Statement(args='throughput mptcp 1s --display', raw='plot throughput mptcp 1s --display', command='plot', arg_list=['throughput', 'mptcp', '1s', '--display'], multiline_command='', terminator='', suffix='', pipe_to=[], output='', output_to='')}
Traceback (most recent call last):
  File "/home/nornetpp/.local/lib/python3.7/site-packages/cmd2/cmd2.py", line 1742, in onecmd_plus_hooks
    stop = self.onecmd(statement)
  File "/home/nornetpp/.local/lib/python3.7/site-packages/cmd2/cmd2.py", line 2050, in onecmd
    stop = func(statement)
  File "/home/nornetpp/.local/lib/python3.7/site-packages/cmd2/cmd2.py", line 222, in cmd_wrapper
    return func(cmd2_instance, args, unknown)
  File "/home/nornetpp/.local/lib/python3.7/site-packages/mptcpanalyzer-0.3-py3.7.egg/mptcpanalyzer/cli.py", line 1150, in do_plot
    raise e
  File "/home/nornetpp/.local/lib/python3.7/site-packages/mptcpanalyzer-0.3-py3.7.egg/mptcpanalyzer/cli.py", line 1144, in do_plot
    result = plotter.run(**dataframes, **dargs)
  File "/home/nornetpp/.local/lib/python3.7/site-packages/mptcpanalyzer-0.3-py3.7.egg/mptcpanalyzer/plot.py", line 240, in run
    fig = self.plot(*pargs, styles=styles, **kwargs)
TypeError: plot() missing 2 required positional arguments: 'dat' and 'destinations'
EXCEPTION of type 'TypeError' occurred with message: 'plot() missing 2 required positional arguments: 'dat' and 'destinations''

**Comment by teto** [comment] 2019-04-26 07:56
I pushed a new release with a `tcp_tput` graph that is just valid for a single TCP (though I haven't checked the results are quite correct yet).
I released a version 0.3.1 since it fixed a few bugs.
I plan to release another version with MPTCP throughput/goodput in 1/2 weeks. And hopefully an updated README/fixed tests.
Closing since this doesn't apply anymore.

**Closed as completed by teto** 2019-04-26 07:56 UTC
